<?php
/**
 * @file
 * Install, update, and uninstall functions for the disable_js module.
 */

/**
 * Implements hook_uninstall().
 */
function disable_js_uninstall() {
  $variables = db_select('variable', 'v')
                ->condition('v.name', 'disable_js_%', 'LIKE')
                ->fields('v', array('name'))
                ->execute()
                ->fetchAll();
  foreach ($variables as $variable) {
    variable_del($variable->name);
  }
}